
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 41;
  public static final int GE = 33;
  public static final int XOR = 37;
  public static final int INTEGER = 4;
  public static final int LPAREN = 39;
  public static final int ARRAY = 7;
  public static final int FOR = 16;
  public static final int MINUS = 24;
  public static final int RPAREN = 40;
  public static final int REVERSE = 18;
  public static final int SEMICOLON = 47;
  public static final int NOT = 38;
  public static final int AND = 35;
  public static final int IS = 11;
  public static final int RANGE = 45;
  public static final int LT = 32;
  public static final int RECORD = 8;
  public static final int TYPE = 3;
  public static final int OR = 36;
  public static final int IN = 17;
  public static final int COMMA = 43;
  public static final int DIV = 26;
  public static final int LOOP = 19;
  public static final int PLUS = 23;
  public static final int ASSIGN = 28;
  public static final int IF = 12;
  public static final int DOT = 44;
  public static final int LE = 34;
  public static final int EOF = 0;
  public static final int BOOLEAN = 5;
  public static final int RETURN = 22;
  public static final int RBRACKET = 42;
  public static final int TRUE = 9;
  public static final int error = 1;
  public static final int MUL = 25;
  public static final int ROUTINE = 21;
  public static final int MOD = 27;
  public static final int REALNUM = 50;
  public static final int EQ = 29;
  public static final int REAL = 6;
  public static final int COLON = 46;
  public static final int ELSE = 14;
  public static final int WHILE = 20;
  public static final int THEN = 13;
  public static final int NE = 30;
  public static final int END = 15;
  public static final int FALSE = 10;
  public static final int GT = 31;
  public static final int VAR = 2;
  public static final int INTEGERNUM = 49;
  public static final int IDENTIFIER = 48;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "TYPE",
  "INTEGER",
  "BOOLEAN",
  "REAL",
  "ARRAY",
  "RECORD",
  "TRUE",
  "FALSE",
  "IS",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "FOR",
  "IN",
  "REVERSE",
  "LOOP",
  "WHILE",
  "ROUTINE",
  "RETURN",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "ASSIGN",
  "EQ",
  "NE",
  "GT",
  "LT",
  "GE",
  "LE",
  "AND",
  "OR",
  "XOR",
  "NOT",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "DOT",
  "RANGE",
  "COLON",
  "SEMICOLON",
  "IDENTIFIER",
  "INTEGERNUM",
  "REALNUM"
  };
}

