package main.lexer;

public enum TokenType {
    // Keywords
    VAR, TYPE, ROUTINE, IS, RECORD, ARRAY, WHILE, FOR, IF, ELSE, END, TRUE, FALSE, INTEGER, REAL, BOOLEAN,
    // Assignment and Operators
    ASSIGN, LT, LE, GT, GE, EQ, NE, PLUS, MINUS, MUL, DIV, MOD,
    // Tokens
    IDENTIFIER, NUMBER, COMMA, SEMICOLON, LPAREN, RPAREN, LBRACKET, RBRACKET,
    DOT, COLON, RANGE, NEWLINE, WHITESPACE, TAB, SINGLE_QUOTE, DOUBLE_QUOTE, UNKNOWN
}